wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.13.9
    cli_version: 0.27.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1779588913
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 63
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 63
      - 80
      3:
      - 2
      - 4
      - 13
      - 42
      4: 3.13.9
      5: 0.27.0
      8:
      - 3
      13: windows-amd64
    e:
      ndbp1ocff2saqsxkssixaiqfsbyr11ff:
        os: Windows-11-10.0.26200-SP0
        python: CPython 3.13.9
        started_at: '2026-05-24T02:15:13.674037Z'
        program: C:\Users\Alex\Documents\Proyecto_Nubes\train.py
        code_path: train.py
        code_path_local: train.py
        git:
          remote_url: https://github.com/SirAlex10/Proyecto_Nubes.git
          commit: 08d6700fb89e0b498ab74c2c83a17afefa87ab85
        root: C:\Users\Alex\Documents\Proyecto_Nubes
        host: AlexPC
        executable: C:\Users\Alex\Documents\Proyecto_Nubes\.venv\Scripts\python.exe
        writer_id: ndbp1ocff2saqsxkssixaiqfsbyr11ff
